### PR TITLE
Fix icons fill

### PR DESCRIPTION
**Pull request by eseQ**
From ugly icons image

to clear as the brilliant view clear as the brilliant

### CODE REVIEW

**Comment by aogaili** [comment]
Good catch, thanks.

But the issue with this fix is that it breaks font awesome which doesn't have a fill attribute defined. I think I'll add currentColor if not fill is defined otherwise we can use whatever the icon set specifies.

**Comment by aogaili** [comment]
Ok I think the last release should fix this issue, give it a try and let me know.

Thanks!

**Comment by eseQ** [comment]
@aliogaili Thanks, the issue has been resolved

**Comment by aogaili** [comment]
Cool, thanks again for the PR, will close this.

**Pull request closed without merging**
